// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TransactionCreateResp transaction create resp
//
// swagger:model TransactionCreateResp
type TransactionCreateResp struct {

	// pay id
	PayID int64 `json:"pay_id,omitempty"`

	// pay url
	PayURL string `json:"pay_url,omitempty"`
}

// Validate validates this transaction create resp
func (m *TransactionCreateResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this transaction create resp based on context it is used
func (m *TransactionCreateResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionCreateResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionCreateResp) UnmarshalBinary(b []byte) error {
	var res TransactionCreateResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
