// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TransactionStatus transaction status
//
// swagger:model TransactionStatus
type TransactionStatus struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this transaction status
func (m *TransactionStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this transaction status based on context it is used
func (m *TransactionStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionStatus) UnmarshalBinary(b []byte) error {
	var res TransactionStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
