// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TransactionCreateBody transaction create body
//
// swagger:model TransactionCreateBody
type TransactionCreateBody struct {

	// amount
	Amount float64 `json:"amount,omitempty"`
}

// Validate validates this transaction create body
func (m *TransactionCreateBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this transaction create body based on context it is used
func (m *TransactionCreateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionCreateBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionCreateBody) UnmarshalBinary(b []byte) error {
	var res TransactionCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
