// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ParamsBody params body
//
// swagger:model ParamsBody
type ParamsBody struct {

	// amount
	Amount float64 `json:"amount,omitempty"`
}

// Validate validates this params body
func (m *ParamsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this params body based on context it is used
func (m *ParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParamsBody) UnmarshalBinary(b []byte) error {
	var res ParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
