// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPITransactionsIDStatusParams creates a new GetAPITransactionsIDStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPITransactionsIDStatusParams() *GetAPITransactionsIDStatusParams {
	return &GetAPITransactionsIDStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPITransactionsIDStatusParamsWithTimeout creates a new GetAPITransactionsIDStatusParams object
// with the ability to set a timeout on a request.
func NewGetAPITransactionsIDStatusParamsWithTimeout(timeout time.Duration) *GetAPITransactionsIDStatusParams {
	return &GetAPITransactionsIDStatusParams{
		timeout: timeout,
	}
}

// NewGetAPITransactionsIDStatusParamsWithContext creates a new GetAPITransactionsIDStatusParams object
// with the ability to set a context for a request.
func NewGetAPITransactionsIDStatusParamsWithContext(ctx context.Context) *GetAPITransactionsIDStatusParams {
	return &GetAPITransactionsIDStatusParams{
		Context: ctx,
	}
}

// NewGetAPITransactionsIDStatusParamsWithHTTPClient creates a new GetAPITransactionsIDStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPITransactionsIDStatusParamsWithHTTPClient(client *http.Client) *GetAPITransactionsIDStatusParams {
	return &GetAPITransactionsIDStatusParams{
		HTTPClient: client,
	}
}

/*
GetAPITransactionsIDStatusParams contains all the parameters to send to the API endpoint

	for the get API transactions ID status operation.

	Typically these are written to a http.Request.
*/
type GetAPITransactionsIDStatusParams struct {

	// ID.
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API transactions ID status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPITransactionsIDStatusParams) WithDefaults() *GetAPITransactionsIDStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API transactions ID status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPITransactionsIDStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API transactions ID status params
func (o *GetAPITransactionsIDStatusParams) WithTimeout(timeout time.Duration) *GetAPITransactionsIDStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API transactions ID status params
func (o *GetAPITransactionsIDStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API transactions ID status params
func (o *GetAPITransactionsIDStatusParams) WithContext(ctx context.Context) *GetAPITransactionsIDStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API transactions ID status params
func (o *GetAPITransactionsIDStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API transactions ID status params
func (o *GetAPITransactionsIDStatusParams) WithHTTPClient(client *http.Client) *GetAPITransactionsIDStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API transactions ID status params
func (o *GetAPITransactionsIDStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API transactions ID status params
func (o *GetAPITransactionsIDStatusParams) WithID(id int64) *GetAPITransactionsIDStatusParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API transactions ID status params
func (o *GetAPITransactionsIDStatusParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPITransactionsIDStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
