// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mc_transaction/internal/http_client/paysystem/models"
)

// PostAPITransactionsReader is a Reader for the PostAPITransactions structure.
type PostAPITransactionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPITransactionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPITransactionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPITransactionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPITransactionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/transactions] PostAPITransactions", response, response.Code())
	}
}

// NewPostAPITransactionsOK creates a PostAPITransactionsOK with default headers values
func NewPostAPITransactionsOK() *PostAPITransactionsOK {
	return &PostAPITransactionsOK{}
}

/*
PostAPITransactionsOK describes a response with status code 200, with default header values.

ОК
*/
type PostAPITransactionsOK struct {
	Payload *models.TransactionCreateResp
}

// IsSuccess returns true when this post Api transactions o k response has a 2xx status code
func (o *PostAPITransactionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api transactions o k response has a 3xx status code
func (o *PostAPITransactionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api transactions o k response has a 4xx status code
func (o *PostAPITransactionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api transactions o k response has a 5xx status code
func (o *PostAPITransactionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api transactions o k response a status code equal to that given
func (o *PostAPITransactionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api transactions o k response
func (o *PostAPITransactionsOK) Code() int {
	return 200
}

func (o *PostAPITransactionsOK) Error() string {
	return fmt.Sprintf("[POST /api/transactions][%d] postApiTransactionsOK  %+v", 200, o.Payload)
}

func (o *PostAPITransactionsOK) String() string {
	return fmt.Sprintf("[POST /api/transactions][%d] postApiTransactionsOK  %+v", 200, o.Payload)
}

func (o *PostAPITransactionsOK) GetPayload() *models.TransactionCreateResp {
	return o.Payload
}

func (o *PostAPITransactionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TransactionCreateResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPITransactionsBadRequest creates a PostAPITransactionsBadRequest with default headers values
func NewPostAPITransactionsBadRequest() *PostAPITransactionsBadRequest {
	return &PostAPITransactionsBadRequest{}
}

/*
PostAPITransactionsBadRequest describes a response with status code 400, with default header values.

Ошибка клиента
*/
type PostAPITransactionsBadRequest struct {
}

// IsSuccess returns true when this post Api transactions bad request response has a 2xx status code
func (o *PostAPITransactionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api transactions bad request response has a 3xx status code
func (o *PostAPITransactionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api transactions bad request response has a 4xx status code
func (o *PostAPITransactionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api transactions bad request response has a 5xx status code
func (o *PostAPITransactionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api transactions bad request response a status code equal to that given
func (o *PostAPITransactionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api transactions bad request response
func (o *PostAPITransactionsBadRequest) Code() int {
	return 400
}

func (o *PostAPITransactionsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/transactions][%d] postApiTransactionsBadRequest ", 400)
}

func (o *PostAPITransactionsBadRequest) String() string {
	return fmt.Sprintf("[POST /api/transactions][%d] postApiTransactionsBadRequest ", 400)
}

func (o *PostAPITransactionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPITransactionsInternalServerError creates a PostAPITransactionsInternalServerError with default headers values
func NewPostAPITransactionsInternalServerError() *PostAPITransactionsInternalServerError {
	return &PostAPITransactionsInternalServerError{}
}

/*
PostAPITransactionsInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostAPITransactionsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this post Api transactions internal server error response has a 2xx status code
func (o *PostAPITransactionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api transactions internal server error response has a 3xx status code
func (o *PostAPITransactionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api transactions internal server error response has a 4xx status code
func (o *PostAPITransactionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api transactions internal server error response has a 5xx status code
func (o *PostAPITransactionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api transactions internal server error response a status code equal to that given
func (o *PostAPITransactionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api transactions internal server error response
func (o *PostAPITransactionsInternalServerError) Code() int {
	return 500
}

func (o *PostAPITransactionsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/transactions][%d] postApiTransactionsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAPITransactionsInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/transactions][%d] postApiTransactionsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAPITransactionsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAPITransactionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
