// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mc_transaction/internal/http_client/paysystem/models"
)

// NewPostAPITransactionsReverseParams creates a new PostAPITransactionsReverseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPITransactionsReverseParams() *PostAPITransactionsReverseParams {
	return &PostAPITransactionsReverseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPITransactionsReverseParamsWithTimeout creates a new PostAPITransactionsReverseParams object
// with the ability to set a timeout on a request.
func NewPostAPITransactionsReverseParamsWithTimeout(timeout time.Duration) *PostAPITransactionsReverseParams {
	return &PostAPITransactionsReverseParams{
		timeout: timeout,
	}
}

// NewPostAPITransactionsReverseParamsWithContext creates a new PostAPITransactionsReverseParams object
// with the ability to set a context for a request.
func NewPostAPITransactionsReverseParamsWithContext(ctx context.Context) *PostAPITransactionsReverseParams {
	return &PostAPITransactionsReverseParams{
		Context: ctx,
	}
}

// NewPostAPITransactionsReverseParamsWithHTTPClient creates a new PostAPITransactionsReverseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPITransactionsReverseParamsWithHTTPClient(client *http.Client) *PostAPITransactionsReverseParams {
	return &PostAPITransactionsReverseParams{
		HTTPClient: client,
	}
}

/*
PostAPITransactionsReverseParams contains all the parameters to send to the API endpoint

	for the post API transactions reverse operation.

	Typically these are written to a http.Request.
*/
type PostAPITransactionsReverseParams struct {

	// Body.
	Body *models.TransactionReverseBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API transactions reverse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPITransactionsReverseParams) WithDefaults() *PostAPITransactionsReverseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API transactions reverse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPITransactionsReverseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API transactions reverse params
func (o *PostAPITransactionsReverseParams) WithTimeout(timeout time.Duration) *PostAPITransactionsReverseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API transactions reverse params
func (o *PostAPITransactionsReverseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API transactions reverse params
func (o *PostAPITransactionsReverseParams) WithContext(ctx context.Context) *PostAPITransactionsReverseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API transactions reverse params
func (o *PostAPITransactionsReverseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API transactions reverse params
func (o *PostAPITransactionsReverseParams) WithHTTPClient(client *http.Client) *PostAPITransactionsReverseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API transactions reverse params
func (o *PostAPITransactionsReverseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API transactions reverse params
func (o *PostAPITransactionsReverseParams) WithBody(body *models.TransactionReverseBody) *PostAPITransactionsReverseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API transactions reverse params
func (o *PostAPITransactionsReverseParams) SetBody(body *models.TransactionReverseBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPITransactionsReverseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
